server:
  port: 8081

spring:
  application:
    name: dubboDemo

dubbo:
  scan:
    base-packages: com.example.dubbo.demo
  protocol:
    name: dubbo
    port: 8099
    host: 192.168.41.3
  registry:
    address: zookeeper://192.168.41.3:2181